### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by osmankudu** [goatslacker/pokemon-go-iv-calculator#5]
module.js:327
    throw err;
    ^

Error: Cannot find module 'chalk'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (-----\src\magic.js:3:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

**Comment by goatslacker** [comment]
`npm install`

I haven't tested the CLI in a bit so I'm unsure about the state of it.

FYI there's a web version http://pocketmaster.surge.sh/
